version: "3"
   
services:
  db:
    image: postgres
    volumes:
      - /mnt/disk1/rfx-services/services/django-ariaform/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.role == manager
         - node.hostname == ${HOSTNAME}

  web:
    image: django-ariaform:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /mnt/disk1/rfx-services/services/django-ariaform/code:/code
    ports:
      - "8087:8000"
    depends_on:
      - db
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.role == manager
         - node.hostname == ${HOSTNAME}