version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ${STORE_DIR}/config:/config
    environment:
      - TZ=America/New_York
    restart: always
    ports:
      - 8123:8123
    links:
      - influxdb
      - telegraf
      - grafana

  # influxdb:
  #   image: influxdb:latest
  #   container_name: influxdb
  #   ports:
  #     - "8083:8083"
  #     - "8086:8086"
  #     - "8090:8090"
  #   env_file:
  #     - 'env.influxdb'
  #   volumes:
  #     # Data persistency
  #     # sudo mkdir -p /srv/docker/influxdb/data
  #     - ${STORE_DIR}/influxdb/data:/var/lib/influxdb
  
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  influxdb:
      image: quay.io/influxdb/influxdb:v2.0.3
      container_name: influxdb
      ports:
        - "8086:8086"
      volumes:
        - ${STORE_DIR}/influxdb/data:/var/lib/influxdb
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    links:
      - influxdb
    volumes:
      - ${STORE_DIR}/grafana/data:/var/lib/grafana
