version: '3'
services:
    tf-build:
        image: bbf-worker:latest
        deploy:
          replicas: 2
        # volumes:
        #    - ${BAZEL_CACHEDIR}:/data
        ports:
            - 8980:8980
