version: '3'
services:
    BVLC_caffe:
        image: ${DOCKER_IMAGE}
        volumes:
            - ${STORE_DIR}/notebooks:/notebooks
        ports:
            - 10010:10010
        deploy:
          replicas: 1
        command: /bin/bash
